/**
 * slug（与 cocktails.json / 路由一致）→ 简体中文常用译名，用于列表与转盘展示。
 * 以当前 public/iba/cocktails.json 共 102 条为准。
 */
export const COCKTAIL_NAME_ZH: Record<string, string> = {
  alexander: '亚历山大',
  americano: '美式',
  'angel-face': '天使之颜',
  aviation: '飞行',
  'bees-knees': '蜜糖金菲士',
  bellini: '贝利尼',
  'between-the-sheets': '枕边细语',
  'black-russian': '黑俄罗斯',
  'bloody-mary': '血腥玛丽',
  boulevardier: '花花公子',
  bramble: '黑莓灌木',
  'brandy-crusta': '白兰地库斯塔',
  caipirinha: '凯匹林纳',
  canchanchara: '坎恰恰拉',
  cardinale: '枢机主教',
  casino: '赌场',
  'champagne-cocktail': '香槟鸡尾酒',
  'chartreuse-swizzle': '查特斯威泽',
  'clover-club': '三叶草俱乐部',
  'corpse-reviver-2': '亡者复生二号',
  cosmopolitan: '大都会',
  'cuba-libre': '自由古巴',
  daiquiri: '戴吉利',
  'dark-n-stormy': '暗夜风暴',
  'dons-special-daiquiri': '唐氏特调戴吉利',
  'dry-martini': '干马天尼',
  'espresso-martini': '浓缩咖啡马天尼',
  fernandito: '费尔南迪托',
  'french-75': '法式75',
  'french-connection': '法式情缘',
  'french-martini': '法式马天尼',
  garibaldi: '加里波第',
  'gin-basil-smash': '金酒罗勒碎',
  'gin-fizz': '金菲士',
  'grand-margarita': '大美格',
  grasshopper: '绿色蚱蜢',
  'hanky-panky': '恶作剧',
  'hemingway-special': '海明威特调',
  'horses-neck': '马颈',
  'iba-tiki': 'IBA 提基',
  illegal: '非法',
  'irish-coffee': '爱尔兰咖啡',
  'john-collins': '约翰科林斯',
  'jungle-bird': '丛林鸟',
  kir: '基尔',
  'last-word': '临别一语',
  'lemon-drop-martini': '柠檬糖马天尼',
  'long-island-iced-tea': '长岛冰茶',
  'mai-tai': '迈泰',
  manhattan: '曼哈顿',
  margarita: '玛格丽特',
  martinez: '马丁内斯',
  'mary-pickford': '玛丽碧克馥',
  mimosa: '含羞草',
  'mint-julep': '薄荷朱莉普',
  'missionarys-downfall': '传教士之陨',
  mojito: '莫吉托',
  'monkey-gland': '猴腺',
  'moscow-mule': '莫斯科骡子',
  'naked-and-famous': '赤裸与声名',
  negroni: '内格罗尼',
  'new-york-sour': '纽约酸酒',
  'old-cuban': '老古巴人',
  'old-fashioned': '古典',
  paloma: '帕洛玛',
  'paper-plane': '纸飞机',
  paradise: '天堂',
  penicillin: '盘尼西林',
  'pina-colada': '椰林飘香',
  'pisco-punch': '皮斯可宾治',
  'pisco-sour': '皮斯可酸酒',
  'planters-punch': '庄园主宾治',
  'porn-star-martini': '艳星马天尼',
  'porto-flip': '波特菲利普',
  'rabo-de-galo': '鸡尾尾羽',
  'ramos-fizz': '拉莫斯金菲士',
  'remember-the-maine': '铭记缅因号',
  'russian-spring-punch': '俄罗斯春日宾治',
  'rusty-nail': '锈钉',
  sazerac: '萨泽拉克',
  'sea-breeze': '海风',
  'sex-on-the-beach': '性感沙滩',
  'sherry-cobbler': '雪莉柯布勒',
  sidecar: '边车',
  'singapore-sling': '新加坡司令',
  'south-side': '南城',
  'spicy-fifty': '五十五香辣',
  spritz: '斯普里茨',
  stinger: '史丁格',
  'suffering-bastard': '受苦混蛋',
  'tequila-sunrise': '龙舌兰日出',
  'three-dots-and-a-dash': '三点一画',
  tipperary: '蒂珀雷里',
  'tommys-margarita': '汤米玛格丽特',
  'trinidad-sour': '特立尼达酸酒',
  tuxedo: '燕尾服',
  've-n-to': '威尼斯托',
  vesper: '维斯帕',
  'vieux-carre': '老广场',
  'whiskey-sour': '威士忌酸酒',
  'white-lady': '白色佳人',
  zombie: '僵尸',
};

export function getCocktailZhName(slug: string, fallbackEnName: string): string {
  return COCKTAIL_NAME_ZH[slug] ?? fallbackEnName;
}
