// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/welcome","name":"welcome","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"*","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"统计","icon":"dotChart","path":"/static","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/user","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/login","layout":false,"id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Static__index" */'@/pages/Static/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__User__UserInfo" */'@/pages/User/UserInfo.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__User__Login" */'@/pages/User/Login.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/data/home/guojia/data/code/guojia/cubing.pro/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/data/home/guojia/data/code/guojia/cubing.pro/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
