// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DotChartOutlined from '/data/home/guojia/data/code/guojia/cubing.pro/node_modules/@ant-design/icons/es/icons/DotChartOutlined';
export default { DotChartOutlined };
