// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DotChartOutlined from '/home/guojia/worker/code/cube/cubing.pro/node_modules/@ant-design/icons/es/icons/DotChartOutlined';
export default { DotChartOutlined };
