/** 自动扩充的常用图标（各约 100 个），由 scripts 逻辑生成 */
import type { ExternalLinkIconEntry } from '@/pages/ExternalLinks/externalLinkIconTypes';
import {
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleOutlined,
  AlipayOutlined,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowsAltOutlined,
  AudioMutedOutlined,
  AudioOutlined,
  AuditOutlined,
  BackwardOutlined,
  BaiduOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  BgColorsOutlined,
  BilibiliOutlined,
  BlockOutlined,
  BoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CameraOutlined,
  CarOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloseSquareOutlined,
  CloudDownloadOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeSandboxOutlined,
  CodepenCircleOutlined,
  CodepenOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CopyrightCircleOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  DashOutlined,
  DashboardOutlined,
  DeleteColumnOutlined,
  DeleteOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffOutlined,
} from '@ant-design/icons';
import {
  FcWorkflow,
  FcWikipedia,
  FcWiFiLogo,
  FcWebcam,
  FcVoicemail,
  FcVoicePresentation,
  FcVlc,
  FcVip,
  FcViewDetails,
  FcVideoProjector,
  FcVideoFile,
  FcUsb,
  FcUpload,
  FcUpRight,
  FcUpLeft,
  FcUp,
  FcUndo,
  FcTwoSmartphones,
  FcTreeStructure,
  FcTrademark,
  FcTouchscreenSmartphone,
  FcTodoList,
  FcTimeline,
  FcTemplate,
  FcTabletAndroid,
  FcSynchronize,
  FcSwitchCamera,
  FcSupport,
  FcStumbleupon,
  FcSteam,
  FcStatistics,
  FcStart,
  FcStackOfPhotos,
  FcSpeaker,
  FcSoundRecordingCopyright,
  FcSmartphoneTablet,
  FcSlrBackSide,
  FcSimCardChip,
  FcSimCard,
  FcSignature,
  FcServices,
  FcServiceMark,
  FcSerialTasks,
  FcSelfie,
  FcSelfServiceKiosk,
  FcScatterPlot,
  FcSalesPerformance,
  FcSafe,
  FcRules,
  FcRuler,
  FcRotateToPortrait,
  FcRotateToLandscape,
  FcRotateCamera,
  FcRightUp2,
  FcRightUp,
  FcRightDown2,
  FcRightDown,
  FcRight,
  FcReuse,
  FcRemoveImage,
  FcRegisteredTrademark,
  FcRefresh,
  FcRedo,
  FcReddit,
  FcReadingEbook,
  FcReading,
  FcRatings,
  FcRadarPlot,
  FcQuestions,
  FcPuzzle,
  FcProcess,
  FcPrivacy,
  FcPrint,
  FcPrevious,
  FcPositiveDynamic,
  FcPortraitMode,
  FcPodiumWithoutSpeaker,
  FcPodiumWithSpeaker,
  FcPodiumWithAudience,
  FcPlus,
  FcPlanner,
  FcPieChart,
  FcPicture,
  FcPhotoReel,
  FcPhoneAndroid,
  FcParallelTasks,
  FcPanorama,
  FcPaid,
  FcPackage,
  FcOvertime,
  FcOrganization,
  FcOrgUnit,
  FcOpenedFolder,
  FcOnlineSupport,
  FcOldTimeCamera,
  FcOk,
  FcNumericalSorting21,
  FcNumericalSorting12,
  FcNook,
  FcNoVideo,
} from 'react-icons/fc';
import {
  GiKeyCard,
  GiCardQueenHearts,
  GiCardKingHearts,
  GiCardJackHearts,
  GiCardAceHearts,
  GiCard9Hearts,
  GiCard8Hearts,
  GiCard7Hearts,
  GiCard6Hearts,
  GiCard5Hearts,
  GiCard4Hearts,
  GiCard3Hearts,
  GiCard2Hearts,
  GiCard10Hearts,
  GiWaterGun,
  GiUpCard,
  GiTreeDoor,
  GiSwipeCard,
  GiStarSkull,
  GiStarKey,
  GiStarFlag,
  GiSkullShield,
  GiSellCard,
  GiLockedHeart,
  GiLockedDoor,
  GiLockedChest,
  GiKeyLock,
  GiIdCard,
  GiHouseKeys,
  GiHeartShield,
  GiHeartKey,
  GiFireShield,
  GiFireGem,
  GiFireBomb,
  GiDragonShield,
  GiDiceShield,
  GiCrownedSkull,
  GiCrownedHeart,
  GiCrownCoin,
  GiCrackedAlienSkull,
  GiCarpetBombing,
  GiCargoShip,
  GiCardboardBox,
  GiCardboardBoxClosed,
  GiCardRandom,
  GiCardQueenSpades,
  GiCardQueenDiamonds,
  GiCardQueenClubs,
  GiCardPlay,
  GiCardPickup,
  GiCardPick,
  GiCardKingSpades,
  GiCardKingDiamonds,
  GiCardKingClubs,
  GiCardJoker,
  GiCardJackSpades,
  GiCardJackDiamonds,
  GiCardJackClubs,
  GiCardExchange,
  GiCardDraw,
  GiCardDiscard,
  GiCardBurn,
  GiCardAceSpades,
  GiCardAceDiamonds,
  GiCardAceClubs,
  GiCard9Spades,
  GiCard9Diamonds,
  GiCard9Clubs,
  GiCard8Spades,
  GiCard8Diamonds,
  GiCard8Clubs,
  GiCard7Spades,
  GiCard7Diamonds,
  GiCard7Clubs,
  GiCard6Spades,
  GiCard6Diamonds,
  GiCard6Clubs,
  GiCard5Spades,
  GiCard5Diamonds,
  GiCard5Clubs,
  GiCard4Spades,
  GiCard4Diamonds,
  GiCard4Clubs,
  GiCard3Spades,
  GiCard3Diamonds,
  GiCard3Clubs,
  GiCard2Spades,
  GiCard2Diamonds,
  GiCard2Clubs,
  GiCard10Spades,
  GiCard10Diamonds,
  GiCard10Clubs,
  GiCarKey,
  GiCarDoor,
  GiBuyCard,
  GiBellShield,
  GiAlienStare,
  GiAlienSkull,
  GiAlienFire,
  GiZeusSword,
} from 'react-icons/gi';

export const OTHER_LINK_ANTD_ICON_ENTRIES_MORE: ExternalLinkIconEntry[] = [
  { name: 'AccountBookOutlined', label: 'AccountBook', Icon: AccountBookOutlined },
  { name: 'AimOutlined', label: 'Aim', Icon: AimOutlined },
  { name: 'AlertOutlined', label: 'Alert', Icon: AlertOutlined },
  { name: 'AlibabaOutlined', label: 'Alibaba', Icon: AlibabaOutlined },
  { name: 'AlignCenterOutlined', label: 'AlignCenter', Icon: AlignCenterOutlined },
  { name: 'AlignLeftOutlined', label: 'AlignLeft', Icon: AlignLeftOutlined },
  { name: 'AlignRightOutlined', label: 'AlignRight', Icon: AlignRightOutlined },
  { name: 'AlipayCircleOutlined', label: 'AlipayCircle', Icon: AlipayCircleOutlined },
  { name: 'AlipayOutlined', label: 'Alipay', Icon: AlipayOutlined },
  { name: 'AliwangwangOutlined', label: 'Aliwangwang', Icon: AliwangwangOutlined },
  { name: 'AliyunOutlined', label: 'Aliyun', Icon: AliyunOutlined },
  { name: 'AmazonOutlined', label: 'Amazon', Icon: AmazonOutlined },
  { name: 'AntCloudOutlined', label: 'AntCloud', Icon: AntCloudOutlined },
  { name: 'AntDesignOutlined', label: 'AntDesign', Icon: AntDesignOutlined },
  { name: 'ApartmentOutlined', label: 'Apartment', Icon: ApartmentOutlined },
  { name: 'AppstoreAddOutlined', label: 'AppstoreAdd', Icon: AppstoreAddOutlined },
  { name: 'AppstoreOutlined', label: 'Appstore', Icon: AppstoreOutlined },
  { name: 'AreaChartOutlined', label: 'AreaChart', Icon: AreaChartOutlined },
  { name: 'ArrowDownOutlined', label: 'ArrowDown', Icon: ArrowDownOutlined },
  { name: 'ArrowLeftOutlined', label: 'ArrowLeft', Icon: ArrowLeftOutlined },
  { name: 'ArrowRightOutlined', label: 'ArrowRight', Icon: ArrowRightOutlined },
  { name: 'ArrowUpOutlined', label: 'ArrowUp', Icon: ArrowUpOutlined },
  { name: 'ArrowsAltOutlined', label: 'ArrowsAlt', Icon: ArrowsAltOutlined },
  { name: 'AudioMutedOutlined', label: 'AudioMuted', Icon: AudioMutedOutlined },
  { name: 'AudioOutlined', label: 'Audio', Icon: AudioOutlined },
  { name: 'AuditOutlined', label: 'Audit', Icon: AuditOutlined },
  { name: 'BackwardOutlined', label: 'Backward', Icon: BackwardOutlined },
  { name: 'BaiduOutlined', label: 'Baidu', Icon: BaiduOutlined },
  { name: 'BankOutlined', label: 'Bank', Icon: BankOutlined },
  { name: 'BarChartOutlined', label: 'BarChart', Icon: BarChartOutlined },
  { name: 'BarcodeOutlined', label: 'Barcode', Icon: BarcodeOutlined },
  { name: 'BarsOutlined', label: 'Bars', Icon: BarsOutlined },
  { name: 'BehanceOutlined', label: 'Behance', Icon: BehanceOutlined },
  { name: 'BehanceSquareOutlined', label: 'BehanceSquare', Icon: BehanceSquareOutlined },
  { name: 'BgColorsOutlined', label: 'BgColors', Icon: BgColorsOutlined },
  { name: 'BilibiliOutlined', label: 'Bilibili', Icon: BilibiliOutlined },
  { name: 'BlockOutlined', label: 'Block', Icon: BlockOutlined },
  { name: 'BoldOutlined', label: 'Bold', Icon: BoldOutlined },
  { name: 'BorderBottomOutlined', label: 'BorderBottom', Icon: BorderBottomOutlined },
  { name: 'BorderHorizontalOutlined', label: 'BorderHorizontal', Icon: BorderHorizontalOutlined },
  { name: 'BorderInnerOutlined', label: 'BorderInner', Icon: BorderInnerOutlined },
  { name: 'BorderLeftOutlined', label: 'BorderLeft', Icon: BorderLeftOutlined },
  { name: 'BorderOuterOutlined', label: 'BorderOuter', Icon: BorderOuterOutlined },
  { name: 'BorderOutlined', label: 'Border', Icon: BorderOutlined },
  { name: 'BorderRightOutlined', label: 'BorderRight', Icon: BorderRightOutlined },
  { name: 'BorderTopOutlined', label: 'BorderTop', Icon: BorderTopOutlined },
  { name: 'BorderVerticleOutlined', label: 'BorderVerticle', Icon: BorderVerticleOutlined },
  { name: 'BorderlessTableOutlined', label: 'BorderlessTable', Icon: BorderlessTableOutlined },
  { name: 'BoxPlotOutlined', label: 'BoxPlot', Icon: BoxPlotOutlined },
  { name: 'BugOutlined', label: 'Bug', Icon: BugOutlined },
  { name: 'BuildOutlined', label: 'Build', Icon: BuildOutlined },
  { name: 'BulbOutlined', label: 'Bulb', Icon: BulbOutlined },
  { name: 'CalculatorOutlined', label: 'Calculator', Icon: CalculatorOutlined },
  { name: 'CameraOutlined', label: 'Camera', Icon: CameraOutlined },
  { name: 'CarOutlined', label: 'Car', Icon: CarOutlined },
  { name: 'CaretDownOutlined', label: 'CaretDown', Icon: CaretDownOutlined },
  { name: 'CaretLeftOutlined', label: 'CaretLeft', Icon: CaretLeftOutlined },
  { name: 'CaretRightOutlined', label: 'CaretRight', Icon: CaretRightOutlined },
  { name: 'CaretUpOutlined', label: 'CaretUp', Icon: CaretUpOutlined },
  { name: 'CarryOutOutlined', label: 'CarryOut', Icon: CarryOutOutlined },
  { name: 'CheckCircleOutlined', label: 'CheckCircle', Icon: CheckCircleOutlined },
  { name: 'CheckOutlined', label: 'Check', Icon: CheckOutlined },
  { name: 'CheckSquareOutlined', label: 'CheckSquare', Icon: CheckSquareOutlined },
  { name: 'CiCircleOutlined', label: 'CiCircle', Icon: CiCircleOutlined },
  { name: 'CiOutlined', label: 'Ci', Icon: CiOutlined },
  { name: 'ClearOutlined', label: 'Clear', Icon: ClearOutlined },
  { name: 'ClockCircleOutlined', label: 'ClockCircle', Icon: ClockCircleOutlined },
  { name: 'CloseCircleOutlined', label: 'CloseCircle', Icon: CloseCircleOutlined },
  { name: 'CloseOutlined', label: 'Close', Icon: CloseOutlined },
  { name: 'CloseSquareOutlined', label: 'CloseSquare', Icon: CloseSquareOutlined },
  { name: 'CloudDownloadOutlined', label: 'CloudDownload', Icon: CloudDownloadOutlined },
  { name: 'CloudServerOutlined', label: 'CloudServer', Icon: CloudServerOutlined },
  { name: 'CloudSyncOutlined', label: 'CloudSync', Icon: CloudSyncOutlined },
  { name: 'CloudUploadOutlined', label: 'CloudUpload', Icon: CloudUploadOutlined },
  { name: 'ClusterOutlined', label: 'Cluster', Icon: ClusterOutlined },
  { name: 'CodeSandboxOutlined', label: 'CodeSandbox', Icon: CodeSandboxOutlined },
  { name: 'CodepenCircleOutlined', label: 'CodepenCircle', Icon: CodepenCircleOutlined },
  { name: 'CodepenOutlined', label: 'Codepen', Icon: CodepenOutlined },
  { name: 'ColumnHeightOutlined', label: 'ColumnHeight', Icon: ColumnHeightOutlined },
  { name: 'ColumnWidthOutlined', label: 'ColumnWidth', Icon: ColumnWidthOutlined },
  { name: 'CommentOutlined', label: 'Comment', Icon: CommentOutlined },
  { name: 'CompressOutlined', label: 'Compress', Icon: CompressOutlined },
  { name: 'ConsoleSqlOutlined', label: 'ConsoleSql', Icon: ConsoleSqlOutlined },
  { name: 'ContactsOutlined', label: 'Contacts', Icon: ContactsOutlined },
  { name: 'ContainerOutlined', label: 'Container', Icon: ContainerOutlined },
  { name: 'ControlOutlined', label: 'Control', Icon: ControlOutlined },
  { name: 'CopyOutlined', label: 'Copy', Icon: CopyOutlined },
  { name: 'CopyrightCircleOutlined', label: 'CopyrightCircle', Icon: CopyrightCircleOutlined },
  { name: 'CopyrightOutlined', label: 'Copyright', Icon: CopyrightOutlined },
  { name: 'CreditCardOutlined', label: 'CreditCard', Icon: CreditCardOutlined },
  { name: 'CrownOutlined', label: 'Crown', Icon: CrownOutlined },
  { name: 'DashOutlined', label: 'Dash', Icon: DashOutlined },
  { name: 'DashboardOutlined', label: 'Dashboard', Icon: DashboardOutlined },
  { name: 'DeleteColumnOutlined', label: 'DeleteColumn', Icon: DeleteColumnOutlined },
  { name: 'DeleteOutlined', label: 'Delete', Icon: DeleteOutlined },
  { name: 'DeleteRowOutlined', label: 'DeleteRow', Icon: DeleteRowOutlined },
  { name: 'DeliveredProcedureOutlined', label: 'DeliveredProcedure', Icon: DeliveredProcedureOutlined },
  { name: 'DeploymentUnitOutlined', label: 'DeploymentUnit', Icon: DeploymentUnitOutlined },
  { name: 'DesktopOutlined', label: 'Desktop', Icon: DesktopOutlined },
  { name: 'DiffOutlined', label: 'Diff', Icon: DiffOutlined },
];

export const OTHER_LINK_FC_ICON_ENTRIES_MORE: ExternalLinkIconEntry[] = [
  { name: 'FcWorkflow', label: 'FcWorkflow', Icon: FcWorkflow },
  { name: 'FcWikipedia', label: 'FcWikipedia', Icon: FcWikipedia },
  { name: 'FcWiFiLogo', label: 'FcWiFiLogo', Icon: FcWiFiLogo },
  { name: 'FcWebcam', label: 'FcWebcam', Icon: FcWebcam },
  { name: 'FcVoicemail', label: 'FcVoicemail', Icon: FcVoicemail },
  { name: 'FcVoicePresentation', label: 'FcVoicePresentation', Icon: FcVoicePresentation },
  { name: 'FcVlc', label: 'FcVlc', Icon: FcVlc },
  { name: 'FcVip', label: 'FcVip', Icon: FcVip },
  { name: 'FcViewDetails', label: 'FcViewDetails', Icon: FcViewDetails },
  { name: 'FcVideoProjector', label: 'FcVideoProjector', Icon: FcVideoProjector },
  { name: 'FcVideoFile', label: 'FcVideoFile', Icon: FcVideoFile },
  { name: 'FcUsb', label: 'FcUsb', Icon: FcUsb },
  { name: 'FcUpload', label: 'FcUpload', Icon: FcUpload },
  { name: 'FcUpRight', label: 'FcUpRight', Icon: FcUpRight },
  { name: 'FcUpLeft', label: 'FcUpLeft', Icon: FcUpLeft },
  { name: 'FcUp', label: 'FcUp', Icon: FcUp },
  { name: 'FcUndo', label: 'FcUndo', Icon: FcUndo },
  { name: 'FcTwoSmartphones', label: 'FcTwoSmartphones', Icon: FcTwoSmartphones },
  { name: 'FcTreeStructure', label: 'FcTreeStructure', Icon: FcTreeStructure },
  { name: 'FcTrademark', label: 'FcTrademark', Icon: FcTrademark },
  { name: 'FcTouchscreenSmartphone', label: 'FcTouchscreenSmartphone', Icon: FcTouchscreenSmartphone },
  { name: 'FcTodoList', label: 'FcTodoList', Icon: FcTodoList },
  { name: 'FcTimeline', label: 'FcTimeline', Icon: FcTimeline },
  { name: 'FcTemplate', label: 'FcTemplate', Icon: FcTemplate },
  { name: 'FcTabletAndroid', label: 'FcTabletAndroid', Icon: FcTabletAndroid },
  { name: 'FcSynchronize', label: 'FcSynchronize', Icon: FcSynchronize },
  { name: 'FcSwitchCamera', label: 'FcSwitchCamera', Icon: FcSwitchCamera },
  { name: 'FcSupport', label: 'FcSupport', Icon: FcSupport },
  { name: 'FcStumbleupon', label: 'FcStumbleupon', Icon: FcStumbleupon },
  { name: 'FcSteam', label: 'FcSteam', Icon: FcSteam },
  { name: 'FcStatistics', label: 'FcStatistics', Icon: FcStatistics },
  { name: 'FcStart', label: 'FcStart', Icon: FcStart },
  { name: 'FcStackOfPhotos', label: 'FcStackOfPhotos', Icon: FcStackOfPhotos },
  { name: 'FcSpeaker', label: 'FcSpeaker', Icon: FcSpeaker },
  { name: 'FcSoundRecordingCopyright', label: 'FcSoundRecordingCopyright', Icon: FcSoundRecordingCopyright },
  { name: 'FcSmartphoneTablet', label: 'FcSmartphoneTablet', Icon: FcSmartphoneTablet },
  { name: 'FcSlrBackSide', label: 'FcSlrBackSide', Icon: FcSlrBackSide },
  { name: 'FcSimCardChip', label: 'FcSimCardChip', Icon: FcSimCardChip },
  { name: 'FcSimCard', label: 'FcSimCard', Icon: FcSimCard },
  { name: 'FcSignature', label: 'FcSignature', Icon: FcSignature },
  { name: 'FcServices', label: 'FcServices', Icon: FcServices },
  { name: 'FcServiceMark', label: 'FcServiceMark', Icon: FcServiceMark },
  { name: 'FcSerialTasks', label: 'FcSerialTasks', Icon: FcSerialTasks },
  { name: 'FcSelfie', label: 'FcSelfie', Icon: FcSelfie },
  { name: 'FcSelfServiceKiosk', label: 'FcSelfServiceKiosk', Icon: FcSelfServiceKiosk },
  { name: 'FcScatterPlot', label: 'FcScatterPlot', Icon: FcScatterPlot },
  { name: 'FcSalesPerformance', label: 'FcSalesPerformance', Icon: FcSalesPerformance },
  { name: 'FcSafe', label: 'FcSafe', Icon: FcSafe },
  { name: 'FcRules', label: 'FcRules', Icon: FcRules },
  { name: 'FcRuler', label: 'FcRuler', Icon: FcRuler },
  { name: 'FcRotateToPortrait', label: 'FcRotateToPortrait', Icon: FcRotateToPortrait },
  { name: 'FcRotateToLandscape', label: 'FcRotateToLandscape', Icon: FcRotateToLandscape },
  { name: 'FcRotateCamera', label: 'FcRotateCamera', Icon: FcRotateCamera },
  { name: 'FcRightUp2', label: 'FcRightUp2', Icon: FcRightUp2 },
  { name: 'FcRightUp', label: 'FcRightUp', Icon: FcRightUp },
  { name: 'FcRightDown2', label: 'FcRightDown2', Icon: FcRightDown2 },
  { name: 'FcRightDown', label: 'FcRightDown', Icon: FcRightDown },
  { name: 'FcRight', label: 'FcRight', Icon: FcRight },
  { name: 'FcReuse', label: 'FcReuse', Icon: FcReuse },
  { name: 'FcRemoveImage', label: 'FcRemoveImage', Icon: FcRemoveImage },
  { name: 'FcRegisteredTrademark', label: 'FcRegisteredTrademark', Icon: FcRegisteredTrademark },
  { name: 'FcRefresh', label: 'FcRefresh', Icon: FcRefresh },
  { name: 'FcRedo', label: 'FcRedo', Icon: FcRedo },
  { name: 'FcReddit', label: 'FcReddit', Icon: FcReddit },
  { name: 'FcReadingEbook', label: 'FcReadingEbook', Icon: FcReadingEbook },
  { name: 'FcReading', label: 'FcReading', Icon: FcReading },
  { name: 'FcRatings', label: 'FcRatings', Icon: FcRatings },
  { name: 'FcRadarPlot', label: 'FcRadarPlot', Icon: FcRadarPlot },
  { name: 'FcQuestions', label: 'FcQuestions', Icon: FcQuestions },
  { name: 'FcPuzzle', label: 'FcPuzzle', Icon: FcPuzzle },
  { name: 'FcProcess', label: 'FcProcess', Icon: FcProcess },
  { name: 'FcPrivacy', label: 'FcPrivacy', Icon: FcPrivacy },
  { name: 'FcPrint', label: 'FcPrint', Icon: FcPrint },
  { name: 'FcPrevious', label: 'FcPrevious', Icon: FcPrevious },
  { name: 'FcPositiveDynamic', label: 'FcPositiveDynamic', Icon: FcPositiveDynamic },
  { name: 'FcPortraitMode', label: 'FcPortraitMode', Icon: FcPortraitMode },
  { name: 'FcPodiumWithoutSpeaker', label: 'FcPodiumWithoutSpeaker', Icon: FcPodiumWithoutSpeaker },
  { name: 'FcPodiumWithSpeaker', label: 'FcPodiumWithSpeaker', Icon: FcPodiumWithSpeaker },
  { name: 'FcPodiumWithAudience', label: 'FcPodiumWithAudience', Icon: FcPodiumWithAudience },
  { name: 'FcPlus', label: 'FcPlus', Icon: FcPlus },
  { name: 'FcPlanner', label: 'FcPlanner', Icon: FcPlanner },
  { name: 'FcPieChart', label: 'FcPieChart', Icon: FcPieChart },
  { name: 'FcPicture', label: 'FcPicture', Icon: FcPicture },
  { name: 'FcPhotoReel', label: 'FcPhotoReel', Icon: FcPhotoReel },
  { name: 'FcPhoneAndroid', label: 'FcPhoneAndroid', Icon: FcPhoneAndroid },
  { name: 'FcParallelTasks', label: 'FcParallelTasks', Icon: FcParallelTasks },
  { name: 'FcPanorama', label: 'FcPanorama', Icon: FcPanorama },
  { name: 'FcPaid', label: 'FcPaid', Icon: FcPaid },
  { name: 'FcPackage', label: 'FcPackage', Icon: FcPackage },
  { name: 'FcOvertime', label: 'FcOvertime', Icon: FcOvertime },
  { name: 'FcOrganization', label: 'FcOrganization', Icon: FcOrganization },
  { name: 'FcOrgUnit', label: 'FcOrgUnit', Icon: FcOrgUnit },
  { name: 'FcOpenedFolder', label: 'FcOpenedFolder', Icon: FcOpenedFolder },
  { name: 'FcOnlineSupport', label: 'FcOnlineSupport', Icon: FcOnlineSupport },
  { name: 'FcOldTimeCamera', label: 'FcOldTimeCamera', Icon: FcOldTimeCamera },
  { name: 'FcOk', label: 'FcOk', Icon: FcOk },
  { name: 'FcNumericalSorting21', label: 'FcNumericalSorting21', Icon: FcNumericalSorting21 },
  { name: 'FcNumericalSorting12', label: 'FcNumericalSorting12', Icon: FcNumericalSorting12 },
  { name: 'FcNook', label: 'FcNook', Icon: FcNook },
  { name: 'FcNoVideo', label: 'FcNoVideo', Icon: FcNoVideo },
];

export const OTHER_LINK_GI_ICON_ENTRIES_MORE: ExternalLinkIconEntry[] = [
  { name: 'GiKeyCard', label: 'GiKeyCard', Icon: GiKeyCard },
  { name: 'GiCardQueenHearts', label: 'GiCardQueenHearts', Icon: GiCardQueenHearts },
  { name: 'GiCardKingHearts', label: 'GiCardKingHearts', Icon: GiCardKingHearts },
  { name: 'GiCardJackHearts', label: 'GiCardJackHearts', Icon: GiCardJackHearts },
  { name: 'GiCardAceHearts', label: 'GiCardAceHearts', Icon: GiCardAceHearts },
  { name: 'GiCard9Hearts', label: 'GiCard9Hearts', Icon: GiCard9Hearts },
  { name: 'GiCard8Hearts', label: 'GiCard8Hearts', Icon: GiCard8Hearts },
  { name: 'GiCard7Hearts', label: 'GiCard7Hearts', Icon: GiCard7Hearts },
  { name: 'GiCard6Hearts', label: 'GiCard6Hearts', Icon: GiCard6Hearts },
  { name: 'GiCard5Hearts', label: 'GiCard5Hearts', Icon: GiCard5Hearts },
  { name: 'GiCard4Hearts', label: 'GiCard4Hearts', Icon: GiCard4Hearts },
  { name: 'GiCard3Hearts', label: 'GiCard3Hearts', Icon: GiCard3Hearts },
  { name: 'GiCard2Hearts', label: 'GiCard2Hearts', Icon: GiCard2Hearts },
  { name: 'GiCard10Hearts', label: 'GiCard10Hearts', Icon: GiCard10Hearts },
  { name: 'GiWaterGun', label: 'GiWaterGun', Icon: GiWaterGun },
  { name: 'GiUpCard', label: 'GiUpCard', Icon: GiUpCard },
  { name: 'GiTreeDoor', label: 'GiTreeDoor', Icon: GiTreeDoor },
  { name: 'GiSwipeCard', label: 'GiSwipeCard', Icon: GiSwipeCard },
  { name: 'GiStarSkull', label: 'GiStarSkull', Icon: GiStarSkull },
  { name: 'GiStarKey', label: 'GiStarKey', Icon: GiStarKey },
  { name: 'GiStarFlag', label: 'GiStarFlag', Icon: GiStarFlag },
  { name: 'GiSkullShield', label: 'GiSkullShield', Icon: GiSkullShield },
  { name: 'GiSellCard', label: 'GiSellCard', Icon: GiSellCard },
  { name: 'GiLockedHeart', label: 'GiLockedHeart', Icon: GiLockedHeart },
  { name: 'GiLockedDoor', label: 'GiLockedDoor', Icon: GiLockedDoor },
  { name: 'GiLockedChest', label: 'GiLockedChest', Icon: GiLockedChest },
  { name: 'GiKeyLock', label: 'GiKeyLock', Icon: GiKeyLock },
  { name: 'GiIdCard', label: 'GiIdCard', Icon: GiIdCard },
  { name: 'GiHouseKeys', label: 'GiHouseKeys', Icon: GiHouseKeys },
  { name: 'GiHeartShield', label: 'GiHeartShield', Icon: GiHeartShield },
  { name: 'GiHeartKey', label: 'GiHeartKey', Icon: GiHeartKey },
  { name: 'GiFireShield', label: 'GiFireShield', Icon: GiFireShield },
  { name: 'GiFireGem', label: 'GiFireGem', Icon: GiFireGem },
  { name: 'GiFireBomb', label: 'GiFireBomb', Icon: GiFireBomb },
  { name: 'GiDragonShield', label: 'GiDragonShield', Icon: GiDragonShield },
  { name: 'GiDiceShield', label: 'GiDiceShield', Icon: GiDiceShield },
  { name: 'GiCrownedSkull', label: 'GiCrownedSkull', Icon: GiCrownedSkull },
  { name: 'GiCrownedHeart', label: 'GiCrownedHeart', Icon: GiCrownedHeart },
  { name: 'GiCrownCoin', label: 'GiCrownCoin', Icon: GiCrownCoin },
  { name: 'GiCrackedAlienSkull', label: 'GiCrackedAlienSkull', Icon: GiCrackedAlienSkull },
  { name: 'GiCarpetBombing', label: 'GiCarpetBombing', Icon: GiCarpetBombing },
  { name: 'GiCargoShip', label: 'GiCargoShip', Icon: GiCargoShip },
  { name: 'GiCardboardBox', label: 'GiCardboardBox', Icon: GiCardboardBox },
  { name: 'GiCardboardBoxClosed', label: 'GiCardboardBoxClosed', Icon: GiCardboardBoxClosed },
  { name: 'GiCardRandom', label: 'GiCardRandom', Icon: GiCardRandom },
  { name: 'GiCardQueenSpades', label: 'GiCardQueenSpades', Icon: GiCardQueenSpades },
  { name: 'GiCardQueenDiamonds', label: 'GiCardQueenDiamonds', Icon: GiCardQueenDiamonds },
  { name: 'GiCardQueenClubs', label: 'GiCardQueenClubs', Icon: GiCardQueenClubs },
  { name: 'GiCardPlay', label: 'GiCardPlay', Icon: GiCardPlay },
  { name: 'GiCardPickup', label: 'GiCardPickup', Icon: GiCardPickup },
  { name: 'GiCardPick', label: 'GiCardPick', Icon: GiCardPick },
  { name: 'GiCardKingSpades', label: 'GiCardKingSpades', Icon: GiCardKingSpades },
  { name: 'GiCardKingDiamonds', label: 'GiCardKingDiamonds', Icon: GiCardKingDiamonds },
  { name: 'GiCardKingClubs', label: 'GiCardKingClubs', Icon: GiCardKingClubs },
  { name: 'GiCardJoker', label: 'GiCardJoker', Icon: GiCardJoker },
  { name: 'GiCardJackSpades', label: 'GiCardJackSpades', Icon: GiCardJackSpades },
  { name: 'GiCardJackDiamonds', label: 'GiCardJackDiamonds', Icon: GiCardJackDiamonds },
  { name: 'GiCardJackClubs', label: 'GiCardJackClubs', Icon: GiCardJackClubs },
  { name: 'GiCardExchange', label: 'GiCardExchange', Icon: GiCardExchange },
  { name: 'GiCardDraw', label: 'GiCardDraw', Icon: GiCardDraw },
  { name: 'GiCardDiscard', label: 'GiCardDiscard', Icon: GiCardDiscard },
  { name: 'GiCardBurn', label: 'GiCardBurn', Icon: GiCardBurn },
  { name: 'GiCardAceSpades', label: 'GiCardAceSpades', Icon: GiCardAceSpades },
  { name: 'GiCardAceDiamonds', label: 'GiCardAceDiamonds', Icon: GiCardAceDiamonds },
  { name: 'GiCardAceClubs', label: 'GiCardAceClubs', Icon: GiCardAceClubs },
  { name: 'GiCard9Spades', label: 'GiCard9Spades', Icon: GiCard9Spades },
  { name: 'GiCard9Diamonds', label: 'GiCard9Diamonds', Icon: GiCard9Diamonds },
  { name: 'GiCard9Clubs', label: 'GiCard9Clubs', Icon: GiCard9Clubs },
  { name: 'GiCard8Spades', label: 'GiCard8Spades', Icon: GiCard8Spades },
  { name: 'GiCard8Diamonds', label: 'GiCard8Diamonds', Icon: GiCard8Diamonds },
  { name: 'GiCard8Clubs', label: 'GiCard8Clubs', Icon: GiCard8Clubs },
  { name: 'GiCard7Spades', label: 'GiCard7Spades', Icon: GiCard7Spades },
  { name: 'GiCard7Diamonds', label: 'GiCard7Diamonds', Icon: GiCard7Diamonds },
  { name: 'GiCard7Clubs', label: 'GiCard7Clubs', Icon: GiCard7Clubs },
  { name: 'GiCard6Spades', label: 'GiCard6Spades', Icon: GiCard6Spades },
  { name: 'GiCard6Diamonds', label: 'GiCard6Diamonds', Icon: GiCard6Diamonds },
  { name: 'GiCard6Clubs', label: 'GiCard6Clubs', Icon: GiCard6Clubs },
  { name: 'GiCard5Spades', label: 'GiCard5Spades', Icon: GiCard5Spades },
  { name: 'GiCard5Diamonds', label: 'GiCard5Diamonds', Icon: GiCard5Diamonds },
  { name: 'GiCard5Clubs', label: 'GiCard5Clubs', Icon: GiCard5Clubs },
  { name: 'GiCard4Spades', label: 'GiCard4Spades', Icon: GiCard4Spades },
  { name: 'GiCard4Diamonds', label: 'GiCard4Diamonds', Icon: GiCard4Diamonds },
  { name: 'GiCard4Clubs', label: 'GiCard4Clubs', Icon: GiCard4Clubs },
  { name: 'GiCard3Spades', label: 'GiCard3Spades', Icon: GiCard3Spades },
  { name: 'GiCard3Diamonds', label: 'GiCard3Diamonds', Icon: GiCard3Diamonds },
  { name: 'GiCard3Clubs', label: 'GiCard3Clubs', Icon: GiCard3Clubs },
  { name: 'GiCard2Spades', label: 'GiCard2Spades', Icon: GiCard2Spades },
  { name: 'GiCard2Diamonds', label: 'GiCard2Diamonds', Icon: GiCard2Diamonds },
  { name: 'GiCard2Clubs', label: 'GiCard2Clubs', Icon: GiCard2Clubs },
  { name: 'GiCard10Spades', label: 'GiCard10Spades', Icon: GiCard10Spades },
  { name: 'GiCard10Diamonds', label: 'GiCard10Diamonds', Icon: GiCard10Diamonds },
  { name: 'GiCard10Clubs', label: 'GiCard10Clubs', Icon: GiCard10Clubs },
  { name: 'GiCarKey', label: 'GiCarKey', Icon: GiCarKey },
  { name: 'GiCarDoor', label: 'GiCarDoor', Icon: GiCarDoor },
  { name: 'GiBuyCard', label: 'GiBuyCard', Icon: GiBuyCard },
  { name: 'GiBellShield', label: 'GiBellShield', Icon: GiBellShield },
  { name: 'GiAlienStare', label: 'GiAlienStare', Icon: GiAlienStare },
  { name: 'GiAlienSkull', label: 'GiAlienSkull', Icon: GiAlienSkull },
  { name: 'GiAlienFire', label: 'GiAlienFire', Icon: GiAlienFire },
  { name: 'GiZeusSword', label: 'GiZeusSword', Icon: GiZeusSword },
];
