import {
  AndroidOutlined,
  ApiOutlined,
  AppleOutlined,
  BellOutlined,
  BookOutlined,
  BranchesOutlined,
  CalendarOutlined,
  ChromeOutlined,
  CloudOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CompassOutlined,
  CustomerServiceOutlined,
  DatabaseOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  ExportOutlined,
  FacebookOutlined,
  FileTextOutlined,
  GithubOutlined,
  GlobalOutlined,
  HomeOutlined,
  ImportOutlined,
  InfoCircleOutlined,
  InstagramOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MessageOutlined,
  PhoneOutlined,
  PictureOutlined,
  QuestionCircleOutlined,
  RocketOutlined,
  SafetyOutlined,
  SettingOutlined,
  ShopOutlined,
  StarOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  TwitterOutlined,
  UnlockOutlined,
  VideoCameraOutlined,
  WechatOutlined,
  YoutubeOutlined,
} from '@ant-design/icons';
import type { ExternalLinkIconComp, ExternalLinkIconEntry } from '@/pages/ExternalLinks/externalLinkIconTypes';
import {
  OTHER_LINK_ANTD_ICON_ENTRIES_MORE,
  OTHER_LINK_FC_ICON_ENTRIES_MORE,
  OTHER_LINK_GI_ICON_ENTRIES_MORE,
} from '@/pages/ExternalLinks/externalLinkIconRegistry.more';
import {
  FcApproval,
  FcBarChart,
  FcBookmark,
  FcBriefcase,
  FcBusiness,
  FcCalendar,
  FcCamera,
  FcClapperboard,
  FcClock,
  FcCollaboration,
  FcCommandLine,
  FcContacts,
  FcDatabase,
  FcFolder,
  FcGlobe,
  FcGoogle,
  FcHome,
  FcKey,
  FcLike,
  FcLink,
  FcLock,
  FcMenu,
  FcMusic,
  FcNews,
  FcPhone,
  FcRating,
  FcSearch,
  FcSettings,
  FcShare,
  FcShipped,
  FcShop,
  FcSms,
  FcSportsMode,
  FcSurvey,
  FcUnlock,
  FcVideoCall,
} from 'react-icons/fc';
import {
  GiAbstract116,
  GiBookmark,
  GiBookshelf,
  GiCalendar,
  GiCastle,
  GiChart,
  GiChessKnight,
  GiChampions,
  GiCrown,
  GiCube,
  GiDiceFire,
  GiEarthAmerica,
  GiEnvelope,
  GiGameConsole,
  GiHearts,
  GiJourney,
  GiLinkedRings,
  GiMedal,
  GiMegaphone,
  GiMeeple,
  GiOpenBook,
  GiPartyPopper,
  GiPhone,
  GiPuzzle,
  GiShield,
  GiSpeedometer,
  GiStarFormation,
  GiStopwatch,
  GiRocket,
  GiTrophy,
  GiWrench,
  GiWorld,
} from 'react-icons/gi';

const OTHER_LINK_ANTD_ICON_ENTRIES_BASE: ExternalLinkIconEntry[] = [
  { name: 'LinkOutlined', label: '链接', Icon: LinkOutlined },
  { name: 'GlobalOutlined', label: '全球', Icon: GlobalOutlined },
  { name: 'HomeOutlined', label: '首页', Icon: HomeOutlined },
  { name: 'BookOutlined', label: '书籍', Icon: BookOutlined },
  { name: 'YoutubeOutlined', label: 'YouTube', Icon: YoutubeOutlined },
  { name: 'GithubOutlined', label: 'GitHub', Icon: GithubOutlined },
  { name: 'TwitterOutlined', label: 'Twitter', Icon: TwitterOutlined },
  { name: 'WechatOutlined', label: '微信', Icon: WechatOutlined },
  { name: 'MailOutlined', label: '邮件', Icon: MailOutlined },
  { name: 'TeamOutlined', label: '团队', Icon: TeamOutlined },
  { name: 'TrophyOutlined', label: '奖杯', Icon: TrophyOutlined },
  { name: 'CalendarOutlined', label: '日历', Icon: CalendarOutlined },
  { name: 'CloudOutlined', label: '云', Icon: CloudOutlined },
  { name: 'ShopOutlined', label: '商店', Icon: ShopOutlined },
  { name: 'VideoCameraOutlined', label: '视频', Icon: VideoCameraOutlined },
  { name: 'PictureOutlined', label: '图片', Icon: PictureOutlined },
  { name: 'FileTextOutlined', label: '文档', Icon: FileTextOutlined },
  { name: 'CodeOutlined', label: '代码', Icon: CodeOutlined },
  { name: 'BranchesOutlined', label: '分支', Icon: BranchesOutlined },
  { name: 'ApiOutlined', label: 'API', Icon: ApiOutlined },
  { name: 'DatabaseOutlined', label: '数据库', Icon: DatabaseOutlined },
  { name: 'AndroidOutlined', label: 'Android', Icon: AndroidOutlined },
  { name: 'AppleOutlined', label: 'Apple', Icon: AppleOutlined },
  { name: 'ChromeOutlined', label: 'Chrome', Icon: ChromeOutlined },
  { name: 'FacebookOutlined', label: 'Facebook', Icon: FacebookOutlined },
  { name: 'InstagramOutlined', label: 'Instagram', Icon: InstagramOutlined },
  { name: 'CustomerServiceOutlined', label: '客服', Icon: CustomerServiceOutlined },
  { name: 'StarOutlined', label: '星标', Icon: StarOutlined },
  { name: 'RocketOutlined', label: '火箭', Icon: RocketOutlined },
  { name: 'ThunderboltOutlined', label: '闪电', Icon: ThunderboltOutlined },
  { name: 'ExperimentOutlined', label: '实验', Icon: ExperimentOutlined },
  { name: 'CompassOutlined', label: '指南针', Icon: CompassOutlined },
  { name: 'EnvironmentOutlined', label: '地点', Icon: EnvironmentOutlined },
  { name: 'PhoneOutlined', label: '电话', Icon: PhoneOutlined },
  { name: 'MessageOutlined', label: '消息', Icon: MessageOutlined },
  { name: 'BellOutlined', label: '通知', Icon: BellOutlined },
  { name: 'SettingOutlined', label: '设置', Icon: SettingOutlined },
  { name: 'ToolOutlined', label: '工具', Icon: ToolOutlined },
  { name: 'SafetyOutlined', label: '安全', Icon: SafetyOutlined },
  { name: 'LockOutlined', label: '锁定', Icon: LockOutlined },
  { name: 'UnlockOutlined', label: '解锁', Icon: UnlockOutlined },
  { name: 'ExportOutlined', label: '导出', Icon: ExportOutlined },
  { name: 'ImportOutlined', label: '导入', Icon: ImportOutlined },
  { name: 'CoffeeOutlined', label: '咖啡', Icon: CoffeeOutlined },
  { name: 'QuestionCircleOutlined', label: '帮助', Icon: QuestionCircleOutlined },
  { name: 'InfoCircleOutlined', label: '信息', Icon: InfoCircleOutlined },
];

export const OTHER_LINK_ANTD_ICON_ENTRIES: ExternalLinkIconEntry[] = [
  ...OTHER_LINK_ANTD_ICON_ENTRIES_BASE,
  ...OTHER_LINK_ANTD_ICON_ENTRIES_MORE,
];

const OTHER_LINK_FC_ICON_ENTRIES_BASE: ExternalLinkIconEntry[] = [
  { name: 'FcGlobe', label: '地球', Icon: FcGlobe },
  { name: 'FcLink', label: '链接', Icon: FcLink },
  { name: 'FcHome', label: '首页', Icon: FcHome },
  { name: 'FcGoogle', label: 'Google', Icon: FcGoogle },
  { name: 'FcFolder', label: '文件夹', Icon: FcFolder },
  { name: 'FcCalendar', label: '日历', Icon: FcCalendar },
  { name: 'FcPhone', label: '电话', Icon: FcPhone },
  { name: 'FcSms', label: '短信', Icon: FcSms },
  { name: 'FcCamera', label: '相机', Icon: FcCamera },
  { name: 'FcVideoCall', label: '视频', Icon: FcVideoCall },
  { name: 'FcMusic', label: '音乐', Icon: FcMusic },
  { name: 'FcSportsMode', label: '运动', Icon: FcSportsMode },
  { name: 'FcLike', label: '喜欢', Icon: FcLike },
  { name: 'FcRating', label: '评分', Icon: FcRating },
  { name: 'FcShipped', label: '物流', Icon: FcShipped },
  { name: 'FcSettings', label: '设置', Icon: FcSettings },
  { name: 'FcMenu', label: '菜单', Icon: FcMenu },
  { name: 'FcSearch', label: '搜索', Icon: FcSearch },
  { name: 'FcNews', label: '新闻', Icon: FcNews },
  { name: 'FcCommandLine', label: '终端', Icon: FcCommandLine },
  { name: 'FcDatabase', label: '数据库', Icon: FcDatabase },
  { name: 'FcCollaboration', label: '协作', Icon: FcCollaboration },
  { name: 'FcLock', label: '锁定', Icon: FcLock },
  { name: 'FcUnlock', label: '解锁', Icon: FcUnlock },
  { name: 'FcApproval', label: '审批', Icon: FcApproval },
  { name: 'FcShop', label: '商店', Icon: FcShop },
  { name: 'FcShare', label: '分享', Icon: FcShare },
  { name: 'FcKey', label: '密钥', Icon: FcKey },
  { name: 'FcBookmark', label: '书签', Icon: FcBookmark },
  { name: 'FcBarChart', label: '图表', Icon: FcBarChart },
  { name: 'FcBriefcase', label: '公文包', Icon: FcBriefcase },
  { name: 'FcBusiness', label: '商务', Icon: FcBusiness },
  { name: 'FcClapperboard', label: '影视', Icon: FcClapperboard },
  { name: 'FcClock', label: '时钟', Icon: FcClock },
  { name: 'FcContacts', label: '联系人', Icon: FcContacts },
  { name: 'FcSurvey', label: '问卷', Icon: FcSurvey },
];

export const OTHER_LINK_FC_ICON_ENTRIES: ExternalLinkIconEntry[] = [
  ...OTHER_LINK_FC_ICON_ENTRIES_BASE,
  ...OTHER_LINK_FC_ICON_ENTRIES_MORE,
];

const OTHER_LINK_GI_ICON_ENTRIES_BASE: ExternalLinkIconEntry[] = [
  { name: 'GiCube', label: '魔方', Icon: GiCube },
  { name: 'GiAbstract116', label: '抽象', Icon: GiAbstract116 },
  { name: 'GiTrophy', label: '奖杯', Icon: GiTrophy },
  { name: 'GiMedal', label: '奖牌', Icon: GiMedal },
  { name: 'GiEarthAmerica', label: '地球', Icon: GiEarthAmerica },
  { name: 'GiBookmark', label: '书签', Icon: GiBookmark },
  { name: 'GiBookshelf', label: '书架', Icon: GiBookshelf },
  { name: 'GiLinkedRings', label: '链接', Icon: GiLinkedRings },
  { name: 'GiMegaphone', label: '喇叭', Icon: GiMegaphone },
  { name: 'GiPartyPopper', label: '庆祝', Icon: GiPartyPopper },
  { name: 'GiPuzzle', label: '拼图', Icon: GiPuzzle },
  { name: 'GiDiceFire', label: '骰子', Icon: GiDiceFire },
  { name: 'GiCrown', label: '王冠', Icon: GiCrown },
  { name: 'GiCastle', label: '城堡', Icon: GiCastle },
  { name: 'GiJourney', label: '旅程', Icon: GiJourney },
  { name: 'GiWorld', label: '世界', Icon: GiWorld },
  { name: 'GiChampions', label: '冠军', Icon: GiChampions },
  { name: 'GiSpeedometer', label: '速度', Icon: GiSpeedometer },
  { name: 'GiStopwatch', label: '秒表', Icon: GiStopwatch },
  { name: 'GiCalendar', label: '日历', Icon: GiCalendar },
  { name: 'GiPhone', label: '电话', Icon: GiPhone },
  { name: 'GiEnvelope', label: '邮件', Icon: GiEnvelope },
  { name: 'GiChart', label: '图表', Icon: GiChart },
  { name: 'GiRocket', label: '火箭', Icon: GiRocket },
  { name: 'GiMeeple', label: '棋子', Icon: GiMeeple },
  { name: 'GiChessKnight', label: '国际象棋', Icon: GiChessKnight },
  { name: 'GiGameConsole', label: '游戏机', Icon: GiGameConsole },
  { name: 'GiStarFormation', label: '星形', Icon: GiStarFormation },
  { name: 'GiWrench', label: '扳手', Icon: GiWrench },
  { name: 'GiHearts', label: '心', Icon: GiHearts },
  { name: 'GiShield', label: '盾', Icon: GiShield },
  { name: 'GiOpenBook', label: '打开的书', Icon: GiOpenBook },
];

export const OTHER_LINK_GI_ICON_ENTRIES: ExternalLinkIconEntry[] = [
  ...OTHER_LINK_GI_ICON_ENTRIES_BASE,
  ...OTHER_LINK_GI_ICON_ENTRIES_MORE,
];

export const OTHER_LINK_ANTD_ICON_MAP: Record<string, ExternalLinkIconComp> = Object.fromEntries(
  OTHER_LINK_ANTD_ICON_ENTRIES.map((e) => [e.name, e.Icon]),
);

export const OTHER_LINK_FC_ICON_MAP: Record<string, ExternalLinkIconComp> = Object.fromEntries(
  OTHER_LINK_FC_ICON_ENTRIES.map((e) => [e.name, e.Icon]),
);

export const OTHER_LINK_GI_ICON_MAP: Record<string, ExternalLinkIconComp> = Object.fromEntries(
  OTHER_LINK_GI_ICON_ENTRIES.map((e) => [e.name, e.Icon]),
);
