// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import dayjs from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs';
import antdPlugin from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/antd-dayjs-webpack-plugin/src/antd-plugin.js';

import isSameOrBefore from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/isSameOrBefore';
import isSameOrAfter from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/isSameOrAfter';
import advancedFormat from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/advancedFormat';
import customParseFormat from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/customParseFormat';
import weekday from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/weekday';
import weekYear from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/weekYear';
import weekOfYear from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/weekOfYear';
import isMoment from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/isMoment';
import localeData from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/localeData';
import localizedFormat from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/localizedFormat';
import duration from '/Users/guojia/worker/code/cube/cubing.pro/node_modules/dayjs/plugin/duration';

dayjs.extend(isSameOrBefore);
dayjs.extend(isSameOrAfter);
dayjs.extend(advancedFormat);
dayjs.extend(customParseFormat);
dayjs.extend(weekday);
dayjs.extend(weekYear);
dayjs.extend(weekOfYear);
dayjs.extend(isMoment);
dayjs.extend(localeData);
dayjs.extend(localizedFormat);
dayjs.extend(duration);

dayjs.extend(antdPlugin);
