export function getDefaultPkArenaSettings() {
    return {
        flagBackgroundEnabled: true,
        scale: 1,
        backgroundColor: '#06060c',
        backgroundColorEnd: '#10101c',
        glowLeft: 'rgba(255, 77, 79, 0.42)',
        glowRight: 'rgba(22, 119, 255, 0.45)',
        stripLeft: 'rgba(255, 77, 79, 0.22)',
        stripRight: 'rgba(22, 119, 255, 0.22)',
        teamNameColor: '#ffffff',
        teamNameFontPx: 30,
        playerNameColor: '#f5f5f5',
        playerNameFontPx: 20,
        pkTitleColor: '#ffffff',
        pkTitleFontPx: 52,
        avatarSizePx: 80,
        diagonalStepPx: 36,
        buttonFontPx: 16,
        barBg: 'rgba(0, 0, 0, 0.35)',
        heroDetailAvatarPx: 300,
        heroDetailNameFontPx: 56,
        heroDetailPkScoreFontPx: 48,
        heroDetailSeedFontPx: 28,
        heroDetailTeamFontPx: 24,
        heroDetailSchoolFontPx: 20,
        heroDetailCryFontPx: 22,
        heroCarouselIntervalMs: 3000,
    };
}
//# sourceMappingURL=pkArenaSettings.js.map